In [1]:
import pandas as pd

In [3]:
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Enrollment_python - 2.xlsx")

In [5]:
data.head()

,Student_ID,Gender,Program,Enrollment_Date,Study_Mode,Tuition_Fee,Enrollment_Status
0,ENR0123,Female,Computer Science,2026-01-06 00:00:00,Full-Time,1037.53,Graduated
1,ENR0050,Female,Public Health,2026-05-02 00:00:00,Full-Time,NaN,Graduated
2,ENR0241,Female,Business Administration,2026-05-19 00:00:00,NaN,823.61,Graduated
3,ENR0279,Female,Computer Science,2025-06-21 00:00:00,Full-Time,998.42,Graduated
4,ENR0091,Male,Engineering,2025-10-03 00:00:00,Online,1358.18,NaN

In [6]:
data.dtypes

Student_ID           object
Gender               object
Program              object
Enrollment_Date      object
Study_Mode           object
Tuition_Fee          object
Enrollment_Status    object
dtype: object

In [7]:
data['Gender'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
295    False
296    False
297    False
298    False
299    False
Name: Gender, Length: 300, dtype: bool

In [8]:
missing_value = data.isnull().sum()

In [9]:
print(missing_value)

Student_ID           15
Gender               15
Program              16
Enrollment_Date      17
Study_Mode           19
Tuition_Fee          15
Enrollment_Status    18
dtype: int64

In [10]:
data = data.isna().mean()* 100

In [11]:
Missing_Percantage = data.isnull().mean() * 100
print(Missing_Percantage)

0.0

In [14]:
import pandas as pd
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Enrollment_python - 2.xlsx")
mode=data["Gender"].mode() [0]
print(mode)

Female

In [15]:
count = data['Gender'].value_counts() [mode]

In [16]:
print ("column:", "Gender")
print ("mode:", mode)
print ("count:", count)

column: Gender
mode: Female
count: 148

In [17]:
import pandas as pd
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Enrollment_python - 2.xlsx")
mode=data["Program"].mode() [0]
print(mode)

Computer Science

In [18]:
mode = data['Gender'].isnull().mean()
print (mode)

0.05

In [19]:
mode = data['Program'].isnull().mean()
print (mode)

0.05333333333333334

In [21]:
mode = data['Study_Mode'].isnull().mean()
print (mode)

0.06333333333333334

In [24]:
mode = data['Enrollment_Date'].mode() [0]
print (mode)

2025-11-26 00:00:00

In [26]:
mode = data['Gender'].mode() [0]
print (mode)

Female

In [25]:
data.dtypes

Student_ID           object
Gender               object
Program              object
Enrollment_Date      object
Study_Mode           object
Tuition_Fee          object
Enrollment_Status    object
dtype: object

In [27]:
mode = data['Enrollment_Status'].mode() [0]
print (mode)

Active

In [28]:
result = []

for Deero in data.columns:
    mode = data[Deero].mode()[0]
    count = data[Deero].value_counts()[mode]
    result.append([Deero, mode, count])

# Convert result into a table
result_table = pd.DataFrame(
    result,
    columns=['Column', 'Mode', 'Count']
)

result_table

/tmp/ipykernel_4149/1723904728.py:4: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'float'
  mode = data[Deero].mode()[0]

              Column                 Mode  Count
0         Student_ID              ENR0026      2
1             Gender               Female    148
2            Program     Computer Science     73
3    Enrollment_Date  2025-11-26 00:00:00      4
4         Study_Mode            Full-Time    159
5        Tuition_Fee               998.42      2
6  Enrollment_Status               Active    174

In [29]:
mode = data['Gender'].isnull().mean()
print (mode)

0.05

In [30]:
mode = data['Program'].isnull().mean()
print (mode)

0.05333333333333334

In [31]:
mode = data['Student_ID'].isnull().mean()
print (mode)

0.05

In [33]:
mode = data['Enrollment_Date'].isnull().mean()
print (mode)

0.056666666666666664

In [34]:
mode = data['Study_Mode'].isnull().mean()
print (mode)

0.06333333333333334

In [35]:
mode = data['Tuition_Fee'].isnull().mean()
print (mode)

0.05

In [36]:
mode = data['Enrollment_Status'].isnull().mean()
print (mode)

0.06

In [37]:
print(missing_value)

Student_ID           15
Gender               15
Program              16
Enrollment_Date      17
Study_Mode           19
Tuition_Fee          15
Enrollment_Status    18
dtype: int64

In [38]:
missing_percentage=data.isnull().mean()*100
print(missing_percentage)

Student_ID           5.000000
Gender               5.000000
Program              5.333333
Enrollment_Date      5.666667
Study_Mode           6.333333
Tuition_Fee          5.000000
Enrollment_Status    6.000000
dtype: float64

In [40]:
data['Program'].value_counts()

Program
Computer Science           73
Data Science               65
Business Administration    46
Engineering                37
Public Health              35
Economics                  25
Unknown                     1
CS                          1
BA                          1
Name: count, dtype: int64

In [42]:
data.isnull().sum()

Student_ID           15
Gender               15
Program              16
Enrollment_Date      17
Study_Mode           19
Tuition_Fee          15
Enrollment_Status    18
dtype: int64